services:
  pythondev:
    image: pythondev:latest
    container_name: todocqrs
    volumes:
      - ./:/app
    ports:
      - 8004:8000
    depends_on:
      - postgredb

  postgredb:
    image: postgres:15.2
    container_name: todocqrspostgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo
    volumes:
      - dbpostgre:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.21
    container_name: todocqrspgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "p4ssw0rd"
    ports:
      - 8200:80
    depends_on:
      - postgredb
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  dbpostgre:
  pgadmin:
